# Matrizes

<a href="https://githubtocolab.com/cn-ufpe/cn-ufpe.github.io/blob/master/material/08_matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab"/></a>

## Inicialização de matrizes

In [1]:
import numpy as np

Inicialização com todos os elementos iguais a zero

In [6]:
A = np.zeros((2, 3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]]


Todos os elementos iguais a 1

In [7]:
B = np.ones((4, 5))
print(B)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Matriz identidade

In [8]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Matriz diagonal

In [9]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [11]:
np.diag([1, 1, 1], 1)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

Matriz aleatória

In [12]:
R = np.random.rand(5,5)
R

array([[0.11925402, 0.11080403, 0.56252364, 0.77258226, 0.91965843],
       [0.06672273, 0.12577862, 0.52730012, 0.21911757, 0.13506361],
       [0.05467231, 0.1364955 , 0.75038035, 0.76287906, 0.72569143],
       [0.71902561, 0.1011851 , 0.4374685 , 0.41016903, 0.89247939],
       [0.25485769, 0.10416753, 0.84068666, 0.58674328, 0.81596789]])

A partir de uma lista

In [13]:
A = [[1, 2, 3, 2], [5, 2, 1, 3], [9, 3, 4, 4]]
A = np.array(A)
print(A)

[[1 2 3 2]
 [5 2 1 3]
 [9 3 4 4]]


### Acessar elementos de uma matriz

In [17]:
A[2, 3]

4

Linhas e colunas com o operador "dois pontos"

In [19]:
linha0 = A[[0],:]
print(linha0)
print(linha0.shape)

[[1 2 3 2]]
(1, 4)


In [23]:
A[0: 2,:]

array([[1, 2, 3, 2],
       [5, 2, 1, 3]])

In [24]:
A[:]

array([[1, 2, 3, 2],
       [5, 2, 1, 3],
       [9, 3, 4, 4]])

In [27]:
A[:, [2]]

array([[3],
       [1],
       [4]])

In [28]:
A[:, 0:3]

array([[1, 2, 3],
       [5, 2, 1],
       [9, 3, 4]])

In [29]:
A[:, [0,3]]

array([[1, 2],
       [5, 3],
       [9, 4]])

### Multiplicação de matrizes

In [30]:
A = np.array([[1, 2, 3], [4, 5, 6], [3, 2, 2]])
b = np.array([[1], [2], [1]])

In [31]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 2]])

In [32]:
b

array([[1],
       [2],
       [1]])

In [33]:
A @ b

array([[ 8],
       [20],
       [ 9]])

In [35]:
print(b.shape)

(3, 1)


In [34]:
b @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

Transposta

In [36]:
b.T @ b

array([[6]])

In [37]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 2]])

In [38]:
A.T

array([[1, 4, 3],
       [2, 5, 2],
       [3, 6, 2]])

In [39]:
vetor = np.array([1, 2, 3])

In [40]:
vetor

array([1, 2, 3])

In [41]:
vetor.T

array([1, 2, 3])

In [42]:
vetor.shape

(3,)

In [43]:
vetor.shape = (3, 1)

In [44]:
vetor.T

array([[1, 2, 3]])

In [45]:
vetor

array([[1],
       [2],
       [3]])