# Fatoração LU

1. Assista o vídeo sobre fatoração LU.
https://youtu.be/MG4Ek9niGTA

A matriz A do vídeo possui fatoração LU, como descrito abaixo.

In [ ]:
import numpy as np
A = np.array([[2, 3, 1, 5], [6, 13, 5, 19], [2, 19, 10, 23], [4, 10, 11, 31]])
print('A = \n', A)
L = np.array([[1, 0, 0, 0], [3, 1, 0, 0], [1, 4, 1, 0], [2, 1, 7, 1]])
U = np.array([[2, 3, 1, 5], [0, 4, 2, 4], [0, 0, 1, 2], [0, 0, 0, 3]])

print()
print('L = \n', L)

print()
print('U = \n', U)

B = L @ U
np.array_equal(B, A)

A = 
 [[ 2  3  1  5]
 [ 6 13  5 19]
 [ 2 19 10 23]
 [ 4 10 11 31]]

L = 
 [[1 0 0 0]
 [3 1 0 0]
 [1 4 1 0]
 [2 1 7 1]]

U = 
 [[2 3 1 5]
 [0 4 2 4]
 [0 0 1 2]
 [0 0 0 3]]


True

2. Determine a fatoração LU da matriz A abaixo e verifique se sua resposta está correta.

$$A = \begin{bmatrix}
4 & -5 & 6 \\
8 & -6 & 7 \\
12 & -7 & 12
\end{bmatrix}$$

# Fatoração Cholesky
3. Assita o vídeo sobre a descomposição de Cholesky
https://youtu.be/bXoGSTBlT5M?t=191


4. Resolva o sistema em https://youtu.be/bXoGSTBlT5M?t=191 utilizando $A^TAx = A^T b$

5. Determine uma matriz triangular inferior $L$, onde $A = LL^T$ e verifique sua resposta.

$$A=\begin{bmatrix}
4 & -2 & 4 \\
-2 & 5 & -4 \\
4 & -4 & 14
\end{bmatrix}$$