# Eliminação gaussiana sem pivoteamento

Antes dessa aula você deve assistir aos vídeos abaixo.

1. [Matrizes com python](https://youtu.be/FgXrDIAlwpk)
1. [Eliminação gaussiana](https://youtu.be/FKPrlNHqwT0)

In [1]:
import numpy as np
import pandas as pd # utilizado apenas na impressão de algumas matrizes

1. **Inicialize uma matriz A de dimensão $3\times 3$ e uma matriz $b$ de dimensão $3 \times 1$ com números aleatórios.**

In [2]:
np.random.seed(2)
A = np.random.rand(3, 3)
b = np.random.rand(3, 1)

Vamos utilizar a eliminação gaussiana para determinar $x$, de modo que $Ax = b$. O python será utilizado como uma calculadora. Para preserver as matrizes `A` e `b` vamos cópias `copia_A` e `copia_b`.

In [3]:
copia_A = np.copy(A)
copia_b = np.copy(b)
print(A)

[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]
 [0.20464863 0.61927097 0.29965467]]


In [4]:
print(b)

[[0.26682728]
 [0.62113383]
 [0.52914209]]


**2. Qual o valor do primeiro multiplicador? Não utilize os números e sim referências a matriz.**

In [5]:
pivo = A[0, 0]
m = -A[1, 0] / pivo

Adicione $m \cdot linha0$ a $linha 1$.

In [6]:
A[1] = m * A[0] + A[1]
b[1] = m * b[0] + b[1]

In [7]:
# Se sua resposta estiver certa A[1,0] será = 0
A

array([[ 0.4359949 ,  0.02592623,  0.54966248],
       [ 0.        ,  0.39448156, -0.21847982],
       [ 0.20464863,  0.61927097,  0.29965467]])

**3. Determine o próximo multiplicador? E atualize a linha 2 da matriz A.**

In [8]:
m = -A[2, 0] / pivo
A[2] = m * A[0] + A[2]
b[2] = m * b[0] + b[2]

In [9]:
# Sua resposta está correta? 
print(A)

[[ 0.4359949   0.02592623  0.54966248]
 [ 0.          0.39448156 -0.21847982]
 [ 0.          0.60710163  0.0416524 ]]


**4. O trabalho com a primeira coluna está finalizado. Determine o próximo pivô.**

In [10]:
pivo = A[1, 1]

**5. Determine o próximo multiplicador e atualize a linha 2.**

In [11]:
m = -A[2, 1] / pivo
A[2] = m * A[1] + A[2]
b[2] = m * b[1] + b[2]

In [12]:
print('A= \n', A)
print()
print('b= \n', b)

A= 
 [[ 0.4359949   0.02592623  0.54966248]
 [ 0.          0.39448156 -0.21847982]
 [ 0.          0.          0.3778898 ]]

b= 
 [[ 0.26682728]
 [ 0.35471813]
 [-0.14200838]]


Agora a matriz A está em um formato triangular superior e precisamos determinar os valores de `x[0]`, `x[1]` e `x[2]`.

In [13]:
x = np.zeros(3)

In [14]:
x

array([0., 0., 0.])

**6. Determine o valor de `x[2]`.**

In [15]:
x[2] = b[2] / A[2, 2]

**7. Determine o valor de `x[1]`.**

In [16]:
x[1] = (b[1] - A[1, 2]*x[2]) / A[1, 1]

**8. Determine o valor de x[0].**

In [17]:
x[0] = (b[0] - A[0, 1]*x[1] - A[0, 2]* x[2]) / A[0, 0]

Verificando o resultado

In [18]:
copia_A @ x

array([0.26682728, 0.62113383, 0.52914209])

In [19]:
copia_b

array([[0.26682728],
       [0.62113383],
       [0.52914209]])

**9. Combine o código que você escreveu até agora para resolver sistemas lineares com 3 equações e 3 incógnitas.**

In [20]:
def eliminacao_gaussiana_3(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes é uma matriz 3 por 3
    termos_independentes é uma matriz 3 por 1
    Não será necessário realizar pivoteamento, se o pivo for igual a zero ocorrerá um erro (divisão por zero)
    '''
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    
    # seu código aqui
    pivo = A[0, 0]
    
    m = -A[1, 0] / pivo
    A[1] = m * A[0] + A[1]
    b[1] = m * b[0] + b[1]
    
    m = -A[2, 0] / pivo
    A[2] = m * A[0] + A[2]
    b[2] = m * b[0] + b[2]
    
    pivo = A[1, 1]
    
    m = -A[2, 1] / pivo
    A[2] = m * A[1] + A[2]
    b[2] = m * b[1] + b[2]
    

    x = np.zeros(3)
    x[2] = b[2] / A[2, 2]
    x[1] = (b[1] - A[1, 2]*x[2]) / A[1, 1]
    x[0] = (b[0] - A[0, 1]*x[1] - A[0, 2]* x[2]) / A[0, 0]
    
    return x

In [21]:
A1 = np.random.rand(3, 3)
b1 = np.random.rand(3, 1) 

In [22]:
x = eliminacao_gaussiana_3(A1, b1)

In [23]:
y = A1 @ x
print('b1 = ', b1)
print('y  = ', y)

b1 =  [[0.0652865 ]
 [0.42812233]
 [0.09653092]]
y  =  [0.0652865  0.42812233 0.09653092]


Agora vamos inicializar uma matriz A com dimensão $5 \times 5$ e uma matriz $b$ com dimensão $5 \times 1$.

In [24]:
A = np.random.rand(5, 5)
b = np.random.rand(5, 1)

In [25]:
print(A)

[[0.12715997 0.59674531 0.226012   0.10694568 0.22030621]
 [0.34982629 0.46778748 0.20174323 0.64040673 0.48306984]
 [0.50523672 0.38689265 0.79363745 0.58000418 0.1622986 ]
 [0.70075235 0.96455108 0.50000836 0.88952006 0.34161365]
 [0.56714413 0.42754596 0.43674726 0.77655918 0.53560417]]


**10. Realize operações sobre linhas para zerar os valores abaixo do pivô.**

In [26]:
pivo = A[0, 0]

m = -A[1, 0] / pivo
A[1] = m * A[0] + A[1]
b[1] = m * b[0] + b[1]

m = -A[2, 0] / pivo
A[2] = m * A[0] + A[2]
b[2] = m * b[0] + b[2]

m = -A[3, 0] / pivo
A[3] = m * A[0] + A[3]
b[3] = m * b[0] + b[3]

m = -A[4, 0] / pivo
A[4] = m * A[0] + A[4]
b[4] = m * b[0] + b[4]

In [27]:
pd.DataFrame(A)

0         1         2         3         4
0  0.12716  0.596745  0.226012  0.106946  0.220306
1  0.00000 -1.173902 -0.420032  0.346191 -0.123008
2  0.00000 -1.984118 -0.104362  0.155084 -0.713030
3  0.00000 -2.323989 -0.745497  0.300164 -0.872448
4  0.00000 -2.233988 -0.571285  0.299572 -0.446980

Agora vamos inicializar uma matriz A com dimensão $10 \times 10$ e uma matriz $b$ com dimensão $10 \times 1$.

In [28]:
A = np.random.rand(10, 10)
b = np.random.rand(10, 1)

**11. Escreva um código para zerar os elementos abaixo do pivô da coluna 0**

In [29]:
pivo = A[0, 0]

for k in range(1, 10):
    m = -A[k, 0] / pivo
    A[k] = m * A[0] + A[k]
    b[k] = m * b[0] + b[k]

In [30]:
pd.DataFrame(A)

0         1         2         3         4         5         6  \
0  4.062750e-01  0.027202  0.247177  0.067144  0.993852  0.970580  0.800258   
1  0.000000e+00  0.504447  0.178349 -0.002748  0.266344 -0.258670 -0.073181   
2  0.000000e+00  0.681039 -0.126987 -0.124489 -1.237920 -1.718278 -1.056176   
3  0.000000e+00  0.381624  0.048453  0.468827 -0.243058 -1.074720 -0.665850   
4  2.775558e-17  0.402382  0.513258  0.626009 -0.354576  0.368893  0.355230   
5  0.000000e+00  0.489875 -0.265021  0.786478 -1.361459 -1.561562 -1.309232   
6  0.000000e+00  0.785511  0.253388  0.076156 -0.897147 -0.964286 -0.650568   
7  1.387779e-17  0.266655 -0.057029  0.611084  0.024658 -0.076894 -0.122533   
8  5.551115e-17  0.517933  0.558308  0.910601 -1.104320 -0.894067 -0.285246   
9  0.000000e+00  0.603356  0.347603 -0.091341 -1.584947 -1.067406 -1.373506   

          7         8         9  
0  0.601817  0.764960  0.169225  
1 -0.110515 -0.291978  0.264837  
2 -1.206920 -0.904371  0.040964  
3 -0.694520 -0.197522  0.450467  
4 -0.183987  0.464787  0.659376  
5 -0.269033 -1.083891  0.207557  
6 -0.201768 -0.899801 -0.066807  
7  0.119948  0.006712  0.239543  
8 -0.536835 -0.017454  0.021046  
9 -1.068176 -1.039487  0.280819

**12. Escreva um código para zerar os elementos abaixo do pivô da coluna 1**

In [31]:
pivo = A[1, 1]

for k in range(2, 10):
    m = -A[k, 1] / pivo
    A[k] = m * A[1] + A[k]
    b[k] = m * b[1] + b[k]

In [32]:
pd.DataFrame(A)

0         1         2         3         4         5         6  \
0  4.062750e-01  0.027202  0.247177  0.067144  0.993852  0.970580  0.800258   
1  0.000000e+00  0.504447  0.178349 -0.002748  0.266344 -0.258670 -0.073181   
2  0.000000e+00  0.000000 -0.367771 -0.120778 -1.597503 -1.369055 -0.957377   
3  0.000000e+00  0.000000 -0.086472  0.470907 -0.444553 -0.879031 -0.610488   
4  2.775558e-17  0.000000  0.370994  0.628201 -0.567031  0.575226  0.413604   
5  0.000000e+00  0.000000 -0.438218  0.789147 -1.620109 -1.310364 -1.238165   
6  0.000000e+00  0.000000 -0.024333  0.080436 -1.311890 -0.561493 -0.536613   
7  1.387779e-17  0.000000 -0.151306  0.612537 -0.116134  0.059841 -0.083849   
8  5.551115e-17  0.000000  0.375191  0.913423 -1.377785 -0.628482 -0.210109   
9  0.000000e+00  0.000000  0.134284 -0.088054 -1.903514 -0.758018 -1.285977   

          7         8         9  
0  0.601817  0.764960  0.169225  
1 -0.110515 -0.291978  0.264837  
2 -1.057716 -0.510181 -0.316584  
3 -0.610913  0.023365  0.250112  
4 -0.095832  0.697689  0.448123  
5 -0.161710 -0.800348 -0.049630  
6 -0.029676 -0.445142 -0.479204  
7  0.178368  0.161053  0.099547  
8 -0.423365  0.282330 -0.250871  
9 -0.935991 -0.690261 -0.035945

**13. Escreva um código para zerar os elementos abaixo do pivô da coluna 2**

In [33]:
pivo = A[2, 2]

for k in range(3, 10):
    m = -A[k, 2] / pivo
    A[k] = m * A[2] + A[k]
    b[k] = m * b[2] + b[k]

**14. Existe repetição nesses códigos. Agora escreva um laço para zerar os elementos abaixo do pivô da coluna 0 até a coluna 8.**

In [34]:
for j in range(0, 9):
    pivo = A[j, j]

    for k in range(j+1, 10):
        m = -A[k, j] / pivo
        A[k] = m * A[j] + A[k]
        b[k] = m * b[j] + b[k]
        A[k, j] = 0

In [35]:
pd.DataFrame(A)

0         1         2         3         4         5         6  \
0  0.406275  0.027202  0.247177  0.067144  0.993852  0.970580  0.800258   
1  0.000000  0.504447  0.178349 -0.002748  0.266344 -0.258670 -0.073181   
2  0.000000  0.000000 -0.367771 -0.120778 -1.597503 -1.369055 -0.957377   
3  0.000000  0.000000  0.000000  0.499304 -0.068942 -0.557134 -0.385385   
4  0.000000  0.000000  0.000000  0.000000 -2.108615 -0.240813 -0.161327   
5  0.000000  0.000000  0.000000  0.000000  0.000000  1.314982  0.591236   
6  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000 -0.207611   
7  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          7         8         9  
0  0.601817  0.764960  0.169225  
1 -0.110515 -0.291978  0.264837  
2 -1.057716 -0.510181 -0.316584  
3 -0.362219  0.143321  0.324549  
4 -0.795475  0.037690 -0.200373  
5  1.619984 -0.452900 -0.318067  
6  0.845483 -0.539353 -0.459331  
7  0.051820  0.135336 -0.375502  
8  0.000000 -3.973728  7.711127  
9  0.000000  0.000000 -2.273556

**15. Escreva uma função que realize a primeira parte da eliminação gaussiana, convertendo a matriz em uma matriz triangular superior.**

In [36]:
def eliminacao_gaussiana(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes é uma matriz 3 por 3
    termos_independentes é uma matriz 3 por 1
    Não será necessário realizar pivoteamento, se o pivo for igual a zero ocorrerá um erro (divisão por zero)
    '''
    
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    tamanho = len(A)

    for j in range(0, tamanho-1):
        pivo = A[j, j]

        for k in range(j+1, 10):
            m = -A[k, j] / pivo
            A[k] = m * A[j] + A[k] # esta linha está realizando muitas operações desnecessárias
            b[k] = m * b[j] + b[k]
            A[k, j] = 0
    
    
    return A, b

In [37]:
A = np.random.rand(10, 10)
b = np.random.rand(10, 1)

tA, tb = eliminacao_gaussiana(A, b)

In [38]:
pd.DataFrame(tA)

0         1         2          3         4          5         6  \
0  0.615255  0.953660  0.448015   0.207050  0.425367   0.444574  0.507617   
1  0.000000  0.010108  0.449742   0.625589  0.191506   0.631420 -0.039587   
2  0.000000  0.000000 -9.034740 -12.189597 -4.185997 -13.159125  1.406327   
3  0.000000  0.000000  0.000000  -0.692479  0.545179  -0.398351  0.225075   
4  0.000000  0.000000  0.000000   0.000000  0.085898  -0.361258  0.913610   
5  0.000000  0.000000  0.000000   0.000000  0.000000   0.982440  0.956903   
6  0.000000  0.000000  0.000000   0.000000  0.000000   0.000000 -5.913844   
7  0.000000  0.000000  0.000000   0.000000  0.000000   0.000000  0.000000   
8  0.000000  0.000000  0.000000   0.000000  0.000000   0.000000  0.000000   
9  0.000000  0.000000  0.000000   0.000000  0.000000   0.000000  0.000000   

          7          8          9  
0  0.525733   0.042429   0.164419  
1  0.096740   0.717325   0.737522  
2 -2.226114 -14.004461 -14.877480  
3  0.249612  -1.157427  -1.309484  
4  0.172351  -0.485086  -0.584740  
5  0.495590   0.057053   1.373083  
6 -1.352265   2.479164   0.118581  
7 -0.381745   1.918173   0.416351  
8  0.000000   3.679322   0.683524  
9  0.000000   0.000000  -0.264442

**16. Agora precisamos determinar as soluções do sistema.**

In [39]:
x = np.zeros(10)

x[9] = tb[9] / tA[9, 9]
x[8] = (tb[8] - tA[8, 9] * x[9]) / tA[8, 8]
x[7] = (tb[7] - tA[7, 8] * x[8] - tA[7, 9] * x[9]) / tA[7, 7]
x[6] = (tb[6] - tA[6, 7] * x[9] - tA[8, 9] * x[9]) / tA[6, 6]

**17. Existe uma repetição no código acima, escreva um laço que calcule os valores de x[k] com k variando de 9 até 0.**

In [41]:
x

array([-3.20238703,  2.81739113, -4.12715503,  3.52250139,  0.67532845,
        3.68550062,  0.00979644, -1.6879322 ,  0.        , -2.82552393])

In [42]:
A @ x

array([ 0.17559907,  0.71332156,  0.88526367,  0.98313836,  0.65290695,
        0.47773635,  0.454958  , -0.65989909, -0.48635441, -0.03942513])

In [43]:
b

array([[0.17559907],
       [0.71332156],
       [0.88526367],
       [0.98313836],
       [0.65290695],
       [0.47773635],
       [0.08778755],
       [0.55895079],
       [0.18115023],
       [0.51440206]])

**18. Escreva uma função que determine as soluções de um sistema com matriz de coeficientes triangular superior**

In [44]:
def triangular_superior(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes: matriz triangular superior
    termos_independentes: termos independentes do sistema retangular superior
    
    retorna a solução do sistema
    '''
    tamanho = len(matriz_coeficientes)
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    
    
    x = np.zeros(tamanho)

    
    return x

In [45]:
triangular_superior(tA, tb)

array([-1.93262526,  1.67369052, -1.69855516,  2.15937314, -0.84411064,
        3.34031026,  0.10878056, -1.23343333,  0.33592332, -2.82552393])

In [46]:
A @ x

array([ 0.17559907,  0.71332156,  0.88526367,  0.98313836,  0.65290695,
        0.47773635,  0.454958  , -0.65989909, -0.48635441, -0.03942513])

In [47]:
b

array([[0.17559907],
       [0.71332156],
       [0.88526367],
       [0.98313836],
       [0.65290695],
       [0.47773635],
       [0.08778755],
       [0.55895079],
       [0.18115023],
       [0.51440206]])

**19. Combine as funções `eliminação_gaussiana` e `triangular_superior` para resolver um sistema de equações Ax=b com $det(A) \neq 0$**

In [48]:
def resolver_sistema(matriz_coeficientes, termos_independentes):
    tA, tb = eliminacao_gaussiana(matriz_coeficientes, termos_independentes)
    x = triangular_superior(tA, tb)
    return x

In [49]:
A = np.random.rand(10, 10)
b = np.random.rand(10, 1)

x = resolver_sistema(A, b)


In [50]:
A @ x

array([0.37538144, 0.19479433, 0.06280544, 0.30860893, 0.71319196,
       0.81318172, 0.3265883 , 0.22028989, 0.32739418, 0.96436684])

In [51]:
b

array([[0.37538144],
       [0.19479433],
       [0.06280544],
       [0.30860893],
       [0.71319196],
       [0.81318172],
       [0.3265883 ],
       [0.22028989],
       [0.32739418],
       [0.96436684]])